const products = [

/* ===================== LUBRIFICANTES ===================== */
{ id: 1, title: "Gel Excitante Unissex Dragão 15ml", price: 41.99, desc: "Proporciona aquecimento e formigamento intenso, aumentando o prazer de ambos os parceiros.", img: "img/Gel_Excitante_Unissex_Dragao_C_965.webp", cat: "lubrificantes" , featured: true},
{ id: 2, title: "Gel Excitante Pinta Clima 15ml", price: 41.99, desc: "Ideal para criar clima e deixar a relação ainda mais envolvente com sensações de excitação imediata.", img: "img/Gel_Excitante_Pinta_Clima_15g__75.webp", cat: "lubrificantes" , featured: true},
{ id: 3, title: "Gel Anestésico Tesão na Raba 15ml", price: 41.99, desc: "Desenvolvido para reduzir a sensibilidade e proporcionar conforto em momentos intensos.", img: "img/Gel_Anestesico_Tesao_Na_Raba_1_877.png", cat: "lubrificantes" , featured: false},
{ id: 4, title: "Gel Retardante Pika Turbo 15ml", price: 41.99, desc: "Ajuda a prolongar o desempenho, retardando a ejaculação sem perder a sensibilidade.", img: "img/Gel_Retardante_Pika_Turbo_15g__146.png", cat: "lubrificantes" , featured: false},
{ id: 5, title: "Vibrador Líquido Power Shock 15ml", price: 41.99, desc: "Fórmula eletrizante que provoca ondas de vibração na região aplicada.", img: "img/Vibrador_Liquido_Power_Shock_2_32.png", cat: "lubrificantes" , featured: false},
{ id: 6, title: "Gel Anestésico InDolor 15ml", price: 41.99, desc: "Perfeito para quem busca mais conforto em penetrações.", img: "img/Gel_Anestesico_InDolor_15g_Sex_506.png", cat: "lubrificantes" , featured: false},
{ id: 7, title: "Gel Sensibilizante Volume Maxi", price: 41.99, desc: "Intensifica a circulação e aumenta a sensibilidade.", img: "img/Gel-Sensibilizante-Volume-Maxi-445.png", cat: "lubrificantes" , featured: true},
{ id: 8, title: "Gel Funcional InTranse 15ml", price: 41.99, desc: "Estimula de forma progressiva, levando a momentos de puro êxtase.", img: "img/Gel_Funcional_InTranse_15g_Sex_83.png", cat: "lubrificantes" , featured: false},
{ id: 9, title: "Gel Excitante Feminino Diaba 15ml", price: 41.99, desc: "Criado especialmente para mulheres, provoca aquecimento e excitação.", img: "img/Gel_Excitante_Feminino_Diaba_H_258.png", cat: "lubrificantes" , featured: false},
{ id: 10, title: "Gel Adstringente Lacradinha 15ml", price: 41.99, desc: "Sensação de estreitamento e prazer intenso.", img: "img/Gel_Adstringente_Lacradinha_15_636.png", cat: "lubrificantes" , featured: false},
{ id: 105, title:"Hot Ice E Vibra Xana Loka 15g Hot Flowers", price: 44.99, desc:"Combinação de calor e frescor com vibração que surpreende.", img:"img/Gel_Funcional_Hot_Ice_E_Vibra__594.jpg", cat:"lubrificantes", featured: true},

/* ===================== AFRODISÍACOS / BEBIDAS ===================== */
{ id: 11, title: "Tesão de Égua", price: 15.99, desc: "Estimulante afrodisíaco que intensifica o desejo.", img: "img/Energetico_Afrodisaco_Feminino_641.webp", cat: "afrodisiacos" , featured: false},
{ id: 12, title: "Energético Afrodisíaco Masculino", price: 15.99, desc: "Aumenta energia e disposição sexual.", img: "img/Energetico_Afrodisaco_Masculin_567.webp", cat: "bebidas" , featured: false},
{ id: 13, title: "Energético Afrodisíaco Feminino", price: 15.99, desc: "Estimula a libido feminina.", img: "img/Energetico_Afrodisaco_Feminino_651.webp", cat: "bebidas" , featured: false},


/* ===================== ACESSÓRIOS ===================== */
{ id: 14, title: "Plug Anal em Aço", price: 43.99, desc: "Plug anal em aço inoxidável, elegante e higiênico.", img: "img/Plug_Anal_Em_Metal_Tamanho_PP__43.jpg", cat: "acessorios" , featured: false},
{ id: 15, title: "Dado Cubo do Amor 2 Unid", price: 19.99, desc: "Jogo erótico divertido para preliminares.", img: "img/Dado_Cubo_Do_Amor_2_Unid_Sexy__880.webp", cat: "acessorios" , featured: false},
{
  id: 16,
  title: "Egg Masturbador",
  price: 40.00,
  desc: "Texturas internas que proporcionam prazer intenso.",
  img: "img/egg-masturbador.webp",

  images: [
    "img/egg-masturbador.webp",
    "img/egg/egg-silky.png",
    "img/egg/egg-spider.png",
    "img/egg/egg-stepper.png",
    "img/egg/egg-twister.png",
    "img/egg/egg-wavy.png"
  ],

  cat: "acessorios",
  featured: true,

  variants: [
    { name: "Clicker" },
    { name: "Silky" },
    { name: "Spider" },
    { name: "Stepper" },
    { name: "Twister" },
    { name: "Wavy" }
  ],

  variantImages: {
    Clicker: ["img/egg/egg-clicker.png"],
    Silky: ["img/egg/egg-silky.png"],
    Spider: ["img/egg/egg-spider.png"],
    Stepper: ["img/egg/egg-stepper.png"],
    Twister: ["img/egg/egg-twister.png"],
    Wavy: ["img/egg/egg-wavy.png"]
  }
},




/* ===================== VIBRADORES ===================== */
{ id: 17, title: "Bullet", price: 43.99, desc: "Mini vibrador discreto, silencioso e potente.", img: "img/Vibrador_Bullet_Ovo_Vibratorio_630.jpg", cat: "vibradores" , featured: false},
{ id: 18, title: "Prótese Ejaculatória sem Vibro", price: 114.99, desc: "Prótese Ejaculatória Kong Com Escroto 19,5x5,5cm Adão E Eva.", img: "img/ProteseEjaculatoriaKong.webp", cat: "vibradores" , featured: false},
{ id: 19, title: "Vibrador Ponto G Premium", price: 43.99, desc: "Design anatômico para estimulação do ponto G.", img: "img/Vibrador_Ponto_G_Golfinho_Liso_516.webp", cat: "vibradores" , featured: false},
{ id: 20, title: "Estimulador Rosa de Ponto G", price: 225.99, desc: "Estimula ponto G e clitóris com design sofisticado.", img: "img/Estimulador_Rosa_De_Ponto_G_E__508.webp", cat: "vibradores", badge: "destaque" , featured: false},
{ id: 21, title: "Anel Peniano", price: 41.99, desc: "Prolonga a ereção e intensifica o prazer do casal.", img: "img/Anel_Peniano_Com_Vibro_Borbole_737.jpg", cat: "acessorios" , featured: false},
{ id: 22, title: "Bolinha Explosiva", price: 18.99, desc: "Libera aroma e líquido beijável excitante.", img: "img/Bolinha_Beijavel_Yummy_Sexy_Fa_672.webp", cat: "bolinhas" , featured: false},
{ id: 23, title: "D4 Gel", price: 41.99, desc: "Excitante unissex de ação rápida.", img: "img/Lubrificante-ntimo-D4-Frozen-6-177.png", cat: "lubrificantes" , featured: false},
{ id: 24, title: "Yummy", price: 20.99, desc: "Gel térmico beijável para brincadeiras orais.", img: "img/Gel_Termico_Comestvel_Yummy_15_809.png", cat: "lubrificantes" , featured: false},
{ id: 25, title: "Yummy Gourmet", price: 41.99, desc: "Versão gourmet do gel beijável.", img: "img/Gel_Termico_Comestvel_Yummy_Go_753.webp", cat: "lubrificantes" , featured: false},
{ id: 26, title: "Prótese c/ Vibro Yaffa", price: 89.99, desc: "Prótese realística com vibração intensa.", img: "img/Protese_Com_Vibro_Interno_195c_800.webp", cat: "vibradores" , featured: false},
{ id: 27, title: "Dados Jogo do Prazer Hot", price: 22.99, desc: "Dados eróticos para apimentar a relação.", img: "img/Dados_Jogo_Do_Prazer_Hot_2_Uni_514.webp", cat: "acessorios" , featured: false},
{ id: 28, title: "Vibrador Ponto G Premium", price: 43.99, desc: "Estimulação intensa do ponto G.", img: "img/Vibrador_Ponto_G_Golfinho_Liso_516.webp", cat: "vibradores" , featured: false},
{ id: 29, title: "Anel Peniano com Vibro", price: 43.99, desc: "Estimula pênis e clitóris simultaneamente.", img: "img/Anel_Peniano_Com_Vibro_Bichinh_860.png", cat: "vibradores" , featured: false},
{ id: 30, title: "Prolongador de Ereção Capitão Bengala", price: 41.99, desc: "Ajuda a manter a ereção por mais tempo.", img: "img/Prolongador-De-Erecao-Capitao--812.png", cat: "lubrificantes" , featured: true},
{ id: 31, title: "Gel Estimulante Pinto Loko", price: 41.99, desc: "Gel divertido que aquece intensamente.", img: "img/Gel_Estimulante_Pinto_Loko_15g_344.webp", cat: "lubrificantes" , featured: true},
{ id: 32, title: "Gel Lubrificante Sedenta Molhada", price: 35.99, desc: "Efeito molhado prolongado.", img: "img/Gel_Lubrificante_Sedenta_Molha_277.jpg", cat: "lubrificantes" , featured: false},
{ id: 33, title: "Lubrificante Beijável Fácil Lub", price: 18.99, desc: "Lubrificante leve e saboroso.", img: "img/Lubrificante_Beijavel_Facil_Lu_757.jpg", cat: "lubrificantes" , featured: false},
{ id: 34, title: "Caneta Beijável", price: 20.99, desc: "Escreva na pele e saboreie.", img: "img/Caneta_Comestvel_Sweet_Body_25_981.jpg", cat: "cosmeticos" , featured: false},
{ id: 35, title: "Perfume de Calcinha Apinil", price: 15.99, desc: "Perfume íntimo feminino sedutor.", img: "img/Perfume-De-Calcinha-40ml-Apini-344.jpg", cat: "cosmeticos" , featured: false},
{ id: 36, title: "Creme Gel Hidratante para Virilha", price: 42.99, desc: "Hidratação delicada para região íntima.", img: "img/Creme_Gel_Hidratante_Para_Viri_413.webp", cat: "cosmeticos" , featured: false},
{ id: 37, title: "Prótese em Cyberskin Sem Vibro", price: 197.99, desc: "Prótese realística em cyberskin.", img: "img/Protese_Em_Cyberskin_Sem_Vibro_449.webp", cat: "vibradores" , featured: false},
{ id: 38, title: "Prótese Real Dick com Escroto", price: 108.99, desc: "Prótese realística com ventosa.", img: "img/Protese_Real_Dick_Com_Escroto__909.webp", cat: "vibradores" , featured: false},
{ id: 39, title: "Aromatizante e Anestésico Oral", price: 42.99, desc: "Dessensibiliza a garganta para sexo oral.", img: "img/Aromatizante_E_Anestesico_Oral_166.webp", cat: "lubrificantes" , featured: false},
{ id: 40, title: "Plug Anal com Led e Controle", price: 134.99, desc: "Plug em silicone com vibração e LED.", img: "img/Plug_Anal_Com_Led_Em_Silicone__173.png", cat: "acessorios", badge: "destaque" , featured: false},
{ id: 41, title: "Baralho Kama Sexy Gay", price: 41.99, desc: "Jogo erótico para casais homoafetivos.", img: "img/Baralho-Kama-Sexy-Gay-Sexy-Fan-458.webp", cat: "jogos" , featured: false},
{ id: 42, title: "Baralho Kama Sutra Completo", price: 43.99, desc: "Cartas com posições do Kama Sutra.", img: "img/Baralho_Kama_Sutra_Completo_Ad_532.webp", cat: "jogos" , featured: false},
{ id: 43, title: "Gel Anestésico Anis Sex 15ml", price: 33.99, desc: "Ajuda a prolongar o prazer com conforto.", img: "img/Gel_Anestesico_Anis_Sex_15ml_S_546.webp", cat: "lubrificantes" , featured: false},
{ id: 44, title: "Energético Afrodisíaco Masculino", price: 15.99, desc: "Mais energia e disposição sexual.", img: "img/Energetico_Afrodisaco_Masculin_567.webp", cat: "bebidas" , featured: false},
{ id: 45, title: "Perfume de Calcinha Hot 40ml", price: 18.99, desc: "Perfume íntimo feminino sensual.", img: "img/Perfume_De_Calcinha_Hot_40ml_B_956.webp", cat: "perfumes" , featured: false},
{ id: 46, title: "Lubrificante Íntimo K-Med 2 em 1 203g", price: 53.99, desc: "Lubrificante para massagem e penetração.", img: "img/Lubrificante0.webp", cat: "lubrificantes" , featured: false},
{ id: 47, title: "Perfume Masculino Phero Aroma", price: 32.99, desc: "Perfume com feromônios.", img: "img/Perfume_Masculino_Phero_Aroma__781.webp", cat: "perfumes" , featured: false},
{ id: 48, title: "Jogo de Cartas Erótico Mau Mau", price: 34.99, desc: "Versão erótica do clássico Mau Mau.", img: "img/Jogo_De_Cartas_Erotico_Mau_Mau_701.webp", cat: "jogos" , featured: false},
{ id: 49, title: "Gel Anestésico Sete Sensações 25g", price: 36.99, desc: "Múltiplas sensações de prazer.", img: "img/Anestesico_Sete_Sensaces_25g_H_41.webp", cat: "lubrificantes" , featured: false},
{ id: 50, title: "Plug Anal Cônico com Rabo de Coelho", price: 45.99, desc: "Plug anal com cauda sensual.", img: "img/Plug_Anal_Cnico_Com_Rabo_De_Co_630.webp", cat: "plugs" , featured: false},
{ id: 51, title: "Plug Anal Dourado Pequeno com Cristal", price: 58.99, desc: "Plug em metal dourado com cristal.", img: "img/Plug_Anal_Dourado_Tamanho_P_Co_309.webp", cat: "plugs", badge: "destaque" , featured: false},
{ id: 52, title: "Plug Anal em Silicone com Vibração", price: 120.99, desc: "Plug flexível com vibração.", img: "img/Plug_Anal_Em_Silicone_Com_Vibr_776.webp", cat: "plugs" , featured: false},
{ id: 53, title: "Plug Anal Escalonado em Aço", price: 50.99, desc: "Plug escalonado para níveis de prazer.", img: "img/Plug_Anal_Escalonado_Em_Aco_Co_757.webp", cat: "plugs" , featured: false},
{ id: 54, title: "Plug Anal Less M Dourado com Rabo", price: 52.99, desc: "Plug com rabo e design elegante.", img: "img/Plug_Anal_Less_M_Dourado_Com_R_240.png", cat: "plugs" , featured: false},
{ id: 55, title: "Prótese com Escroto e Ventosa", price: 129.99, desc: "Prótese com escroto e ventosa.", img: "img/Protese_Com_Escroto_E_Ventosa__15.webp", cat: "proteses" , featured: false},
{ id: 56, title: "Algema de Metal com Pelúcia", price: 64.99, desc: "Dominação leve e segura.", img: "img/Algema_De_Metal_Com_Pelucia_Ha_63.webp", cat: "acessorios" , featured: false},
{ id: 57, title: "Algema em Couro Sintético", price: 43.99, desc: "Resistente e confortável.", img: "img/Algema_Em_Couro_Sintetico_Bras_611.webp", cat: "acessorios" , featured: false},
{ id: 58, title: "Algema para Mãos e Pés", price: 82.99, desc: "Para jogos de dominação intensos.", img: "img/Algema_Para_Maos_E_Pes_Brasil__660.webp", cat: "acessorios" , featured: false},
{ id: 59, title: "Anestésico Anal Rebelde 15ml", price: 28.99, desc: "Reduz sensibilidade anal.", img: "img/Anestesico_Anal_Rebelde_Sem_Ca_116.webp", cat: "lubrificantes" , featured: false},
{ id: 60, title: "Bolinha Excitante Goze Sexy", price: 20.99, desc: "Explode liberando aroma afrodisíaco.", img: "img/Bolinha_Excitante_Goze___Sexy__716.webp", cat: "bolinhas" , featured: false},
{ id: 61, title: "Bolinha Excitante Power Shock", price: 20.99, desc: "Sensações eletrizantes intensas.", img: "img/Bolinha_Excitante_Power_Shock__531.webp", cat: "bolinhas" , featured: false},
{ id: 62, title: "Bomba Peniana Manual de Água", price: 179.99, desc: "Auxilia na ereção.", img: "img/Bomba_Peniana_Manual_De_Agua_I_664.webp", cat: "acessorios", badge: "destaque" , featured: false},
{ id: 63, title: "Chicote com Franja 40cm", price: 42.99, desc: "Acessório para dominação.", img: "img/Chicote_Com_Franja_40cm_Sexy_F_1.webp", cat: "acessorios" , featured: false},
{ id: 64, title: "Chicote com Tiras 50 Tons", price: 39.99, desc: "Inspirado em 50 Tons de Cinza.", img: "img/Chicote_Com_Tiras_50_Tons_Bras_932.webp", cat: "acessorios" , featured: false},
{ id: 65, title: "Chicote Reforçado com 6 Tiras", price: 29.99, desc: "Mais intensidade e resistência.", img: "img/Chicote_Reforcado_Com_6_Tiras__187.webp", cat: "acessorios" , featured: false},
{ id: 66, title: "Energético Afrodisíaco Feminino", price: 15.99, desc: "Estimula a libido feminina.", img: "img/Energetico_Afrodisaco_Feminino_651.webp", cat: "bebidas" , featured: false},
{ id: 67, title: "Estimulador Rosa de Ponto G", price: 225.99, desc: "Estimula ponto G e clitóris.", img: "img/Estimulador_Rosa_De_Ponto_G_E__508.webp", cat: "vibradores" , featured: false},
{ id: 68, title: "Excitante Goze Sexy 15g", price: 41.99, desc: "Gel excitante que aquece.", img: "img/Excitante_Goze__15g_Sexy_Fanta_498.webp", cat: "lubrificantes" , featured: false},
{ id: 69, title: "Excitante Lucifer em Spray 25ml", price: 35.99, desc: "Potencializa o prazer rapidamente.", img: "img/Excitante_Lucifer_em_Spray_25m_209.webp", cat: "lubrificantes" , featured: false},
{ id: 70, title: "Excitante Masculino Volumão 25ml", price: 32.99, desc: "Sensação de aumento e potência.", img: "img/Excitante_Masculino_Volumao_25_683.webp", cat: "lubrificantes" , featured: false},
{ id: 71, title: "Excitante Pau de Cavalo 40ml", price: 25.99, desc: "Conhecido pela potência intensa.", img: "img/Excitante_Pau_De_Cavalo_40ml_B_415.webp", cat: "lubrificantes" , featured: false},
{ id: 72, title: "Gel Anestésico Nocucedim 18ml", price: 25.99, desc: "Anestesia suave para conforto.", img: "img/Gel_Anestesico_Nocucedim_18ml__564.webp", cat: "lubrificantes" , featured: false},
{ id: 73, title: "Gel Comestível Power Black 35ml", price: 28.99, desc: "Gel com sabor irresistível.", img: "img/Gel_Comestvel_Power_Black_35ml_576.webp", cat: "lubrificantes" , featured: false},
{ id: 74, title: "Gel Funcional Pikasso 18g", price: 41.99, desc: "Intensifica o prazer.", img: "img/Gel_Funcional_Pikasso_18g_Pepp_28.webp", cat: "lubrificantes" , featured: false},
{ id: 75, title: "Máscara em Couro", price: 189.99, desc: "Máscara fetichista para dominação.", img: "img/Mascara_Em_Couro_Sd_Clothing_138.webp", cat: "acessorios", badge: "destaque" , featured: false},
{ id: 76, title: "Masturbador Lanterna com Vagina", price: 110.99, desc: "Textura realística em formato de lanterna.", img: "img/Masturbador_Lanterna_Com_Vagin_911.webp", cat: "masturbadores" , featured: false},
{ id: 77, title: "Mini Masturbador Lanterna", price: 108.99, desc: "Versão compacta do masturbador lanterna.", img: "img/Mini_Masturbador_Lanterna_Em_F_737.webp", cat: "masturbadores" , featured: false},
{ id: 78, title: "Perfume de Cueca 40ml", price: 22.99, desc: "Perfume íntimo masculino.", img: "img/Perfume-De-Cueca-40ml-Apinil-619.png", cat: "perfumes" , featured: false},
{ id: 79, title: "Preservativo Efeito Retardante", price: 18.99, desc: "Ajuda a prolongar a relação.", img: "img/Preservativo_Efeito_Retardante_317.webp", cat: "preservativos" , featured: false},
{ id: 80, title: "Preservativo Aromas Sortidos", price: 17.99, desc: "Sabores variados para diversão.", img: "img/Preservativo_Masculino_Aromas__979.webp", cat: "preservativos" , featured: false},
{ id: 81, title: "Preservativo Extra Fino", price: 23.99, desc: "Mais sensibilidade sem perder a proteção.", img: "img/Preservativo_Masculino_Extrafi_402.webp", cat: "preservativos" , featured: false},
{ id: 82, title: "Sabonete Masculino For Men 200ml", price: 17.99, desc: "Higiene íntima com frescor duradouro.", img: "img/Sabonete-Masculino-For-Men-200-794.png", cat: "higiene" , featured: false},
{ id: 83, title: "Varinha Mágica Libre 12 Modos", price: 112.99, desc: "Vibrador varinha com múltiplos modos de pulsação.", img: "img/Varinha_Magica_Libre_12_Modos__834.webp", cat: "vibradores" , featured: false},
{ id: 84, title: "Venda Tapa Olhos em Pelúcia", price: 21.99, desc: "Venda confortável para experiências sensoriais.", img: "img/Venda_Tapa_Olhos_Em_Pelucia_Br_210.webp", cat: "acessorios" , featured: false},
{ id: 85, title: "Vibrador de Pulsação Ponto G", price: 217.99, desc: "Estimulação profunda com pulsações.", img: "img/Vibrador_De_Pulsacao_Ponto_G_E_889.webp", cat: "vibradores", badge: "destaque" , featured: false},
{ id: 86, title: "Vibrador e Estimulador de Clitóris", price: 243.99, desc: "Estimula clitóris e ponto G.", img: "img/Vibrador_E_Estimulador_De_Clit_52.webp", cat: "vibradores" , featured: false},
{ id: 87, title: "Vibrador Ponto G com Função Pulsar", price: 163.99, desc: "Design sofisticado com função pulsar.", img: "img/Vibrador_Ponto_G_Com_Funcao_Pu_581.webp", cat: "vibradores" , featured: false},
{ id: 88, title: "Vibrador Rosa Dupla Importação", price: 367.99, desc: "Design exclusivo com dupla estimulação.", img: "img/Vibrador_Rosa_Dupla_Importacao_442.webp", cat: "vibradores", badge: "destaque" , featured: false},
{ id: 89, title: "Gel Massageador Sebo de Carneiro 250g", price: 10.99, desc: "Relaxamento e alívio muscular.", img: "img/Gel_Massageador_PTD_Sebo_De_Ca_818.webp", cat: "massagem" , featured: false},
{ id: 90, title: "Gel Aromatizante para Virilha Glow 250ml", price: 35.99, desc: "Aromatiza e hidrata a virilha.", img: "img/Gel_Aromatizante_Para_Virilha__417.webp", cat: "cosmeticos" , featured: false},
{ id: 91, title: "Gel Funcional Anal Kuloko 15g", price: 41.99, desc: "Conforto e prazer anal.", img: "img/Gel_Funcional_Anal_Kuloko_15g__395.webp", cat: "lubrificantes" , featured: false},
{ id: 92, title: "Gel Anestésico Fofa Toba 15ml", price: 27.99, desc: "Reduz sensibilidade anal.", img: "img/Gel_Anestesico_Fofa_Toba_15ml__63.webp", cat: "lubrificantes" , featured: false},
{ id: 93, title: "Óleo Térmico Beijável La Pimienta 15ml", price: 23.99, desc: "Aquece suavemente e tem sabor delicioso.", img: "img/Oleo_Termico_Beijavel_15ml_La__911.webp", cat: "massagem" , featured: false},
{ id: 94, title: "Sabonete Íntimo Soul Soft 200ml", price: 12.99, desc: "Limpeza suave com pH equilibrado.", img: "img/Sabonete_ntimo_Soul_Soft_200ml_532.webp", cat: "higiene" , featured: false},
{ id: 95, title: "Excitante em Gotas Esquenta e Esfria 17ml", price: 41.99, desc: "Sensações alternadas de calor e frio.", img: "img/Excitante_Em_Gotas_Esquenta_E__254.webp", cat: "lubrificantes" , featured: false},
{
  id: 96,
  title: "Sabonete Íntimo Soul Cosméticos 200ml",
  price: 12.99,
  desc: "Frescor e higiene diária.",
  img: "img/Sabonete_ntimo_200ml_Soul_Cosm_820.webp",
  images: [
    "img/Sabonete_ntimo_200ml_Soul_Cosm_820.webp",
    "img/Sabonete_uva.webp",
    "img/sabonete/morango.webp",
    "img/sabonete/melancia.jpeg",
    "img/sabonete/aroeira.webp",
    "img/sabonete/menta.webp",
    "img/sabonete/petalas de rosa.webp",
    "img/sabonete/pitaya.webp",
    "img/sabonete/chocolate com pimenta.webp",
    "img/sabonete/barbatimão.webp",
    "img/sabonete/black.webp",
    "img/sabonete/tutti-frutti.webp",
  ],
  cat: "higiene",
  featured: true,
  variants: [
    { name: "Uva" },
    { name: "Barbatimão" },
    { name: "Morango" },
    { name: "Aroeira" },
    { name: "Menta" },
    { name: "Melancia Fresh" },
    { name: "Pitaya Cremosa" },
    { name: "Pétalas de Rosa" },
    { name: "Chocolate com Pimenta" },
    { name: "Talco" },
    { name: "Maçã Verde" },
    { name: "Black Haus" },
    { name: "17 Ervas" },

  ]
},

{ id: 97, title: "Lubrificante Íntimo D4 Sachê 5g", price: 5.99, desc: "Lubrificante prático em sachê.", img: "img/Lubrificante_ntimo_D4_Sach_5g__257.webp", cat: "lubrificantes" , featured: false},
{ id: 98, title: "Lubrificante Íntimo K-Med 2 em 1 50g", price: 25.99, desc: "Lubrificante hidratante e funcional.", img: "img/Lubrificante_ntimo_Kmed_2_Em_1_429.webp", cat: "lubrificantes" , featured: false},
{ id: 99, title: "Lubrificante Sedenta por Conforto 50g", price: 35.99, desc: "Lubrificante premium de conforto.", img: "img/Lubrificante_Sedenta_Por_Confo_612.webp", cat: "lubrificantes" , featured: false},
{ id: 100, title: "Garganta Profunda 15ml", price: 58.99, desc: "Conforto para sexo oral.", img: "img/Gel_Anestesico_Garganta_Profun.webp", cat: "lubrificantes" , featured: false},
{ id: 101, title: "Ducha Higiênica Unissex 89ml", price: 25.99, desc: "Ducha prática e discreta.", img: "img/Ducha_Higinica_Unissex.png", cat: "higiene" , featured: false},
{ id: 102, title: "Ducha Higiênica 230ml", price: 38.99, desc: "Limpeza íntima completa.", img: "img/Ducha_Higinica_230ml.webp", cat: "higiene" , featured: false},
{ id: 103, title: "Lubrificante Íntimo K-Med Ice 50g", price: 36.99, desc: "Efeito refrescante intenso.", img: "img/Lubrificante_ntimo_Kmed_Ice.webp", cat: "lubrificantes" , featured: false},
{ id: 104, title: "Lubrificante Íntimo K-Med Hot 200g", price: 65.99, desc: "Efeito quente para mais prazer.", img: "img/Lubrificante_ntimo_Kmed_Hot_20_600.webp", cat: "lubrificantes" , featured: false},

];
